events {}
http {
  server {
    listen 80;
    location ~ ^/(graphql|rest|media|static|checkout|customer|paypal|braintree|headora)/ { proxy_pass http://magento:8080; }
    location / { proxy_pass http://nextjs:3000; }
  }
}
